Override branch and commit in coverage workflow

diff --git a/.github/workflows/code-coverage.yml b/.github/workflows/code-coverage.yml
--- a/.github/workflows/code-coverage.yml
+++ b/.github/workflows/code-coverage.yml
@@ -26,6 +26,13 @@ jobs:
           cmake -B build -DCMAKE_BUILD_TYPE=Release -DCOVERAGE=ON && cmake --build build -- -j4
           ./build/cpu/openmp.out --reporters=console --success
 
+      - name: Check coverage file
+        run: |
+          if [ ! -s coverage_filtered.info ]; then
+            echo "Error: Coverage file is empty"
+            exit 1
+          fi
+
       - name: Create coverage report
         working-directory: ${{github.workspace}}/tests/build
         run: |
@@ -39,4 +46,7 @@ jobs:
           flags: unittests
           name: codecov-umbrella
           fail_ci_if_error: true
+          verbose: true
+          override_branch: ${{ github.ref_name }}
+          override_commit: ${{ github.sha }}
 
